spring:
  application:
    name: JournalApp
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster0.2mtww.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
    redis:
      host: redis-15713.crce179.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 15713
      userName: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls :
            enable: true
server:
  port: 8082
#  servlet:
#    context-path: /journal
#logging:
#  level:
#    com:
#      AsiaAutmation:
#        JournalApp: DEBUG
#logging:
#  level:
#    com:
#      AsiaAutmation:
#        JournalApp:
#          UserService: DEBUG
weather:
  api:
    key: ${WEATHER_API_KEY}